### ISSUE TITLE
contents for section "Configuring CernVM-FS on HPC infrastructure"

### ISSUE THREAD

**Issue by boegel** [multixscale/cvmfs-tutorial-hpc-best-practices#6]

**Comment by stderr-enst** [comment]
Alan suggested I should mention a scenario that we ran in lately:

When configuring CVMFS repos to be mounted on RHEL <9 distros, you might want to consider statically mounting CVMFS repos via `/etc/fstab` or alternatively increasing the autofs timeout, e.g. via `OPTIONS="-t 3600"` in `/etc/sysconfig/autofs`.

Both prevent a situation where jobs running inside containers and autofs automatic unmount might overlap, resulting in a machine-wide locked-up cvmfs repo.

Some reference, but maybe not the best to explain the issue: https://github.com/cvmfs/cvmfs/issues/3402

Since they mentioned that this shouldn't occur anymore in RHEL >=9 distros, this is only a weak argument for a general recommendation.
Maybe also something for the troubleshoot section, instead of the general config section?

**Comment by boegel** [comment]
> Using "-t 0" so that autofs never unmounts is preferable to static mounts.

@DrDaveD Can you clarify why that's the case?

I'm working on including this recommendation in PR #20, it would be good to also briefly mention the reasoning for it.

**Comment by boegel** [comment]
@bedroge Can you add a line (or two) on that the `access/client/#recommendations-for-autofs` after #20 gets merged?

**Comment by bedroge** [comment]
> @bedroge Can you add a line (or two) on that the `access/client/#recommendations-for-autofs` after #20 gets merged?

Assuming you meant the autofs vs static mount thing, done in https://github.com/multixscale/cvmfs-tutorial-hpc-best-practices/pull/26.

Do you also want to add a warning box about the Slurm issue? Don't know how many clusters are actually using that job_container plugin.

**Comment by DrDaveD** [comment]
> > Using "-t 0" so that autofs never unmounts is preferable to static mounts.
> 
> @DrDaveD Can you clarify why that's the case?
> 
> I'm working on including this recommendation in PR #20, it would be good to also briefly mention the reasoning for it.

Because it's a lot less configuration, and the configuration does not need to be updated every time new repositories are added to a domain.  This way it can still discover new repositories, they just stay mounted once they're used.
